[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# 禁用子模块检出
[build.processing]
  skip_submodules = true

# 处理SPA路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 缓存静态资源
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"